---
title: "Compulsory Exercise 2: Predicting AirBnB-prices in Rome"
author:
- Helle Villmones Haug
- Hjalmar Jacob Vinje
- Sanna Baug Warholm
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes: \usepackage{amsmath}
output:
  # html_document:
  #   toc: no
  #   toc_depth: '2'
  #   df_print: paged
  pdf_document:
    toc: no
    toc_depth: '2'
urlcolor: blue
abstract: "This is the place for your abstract (max 350 words)"
---
  
```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE,message=FALSE,warning=FALSE,strip.white=TRUE,prompt=FALSE,
                      cache=TRUE, size="scriptsize",fig.width=4, fig.height=3,fig.align = "center")
```

```{r,eval=TRUE,echo=FALSE}
library("knitr")
library("rmarkdown")
```

<!--  Etc (load all packages needed). -->





## Introduction: Scope and purpose of your project


## Descriptive data analysis/statistics



## Methods
### Method 1 (Tree-based?)

### Method 2 (Something more fancy, gradient boosting mabye?)

## Results and interpretation


## Summary